---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# Build targets can be found at:
# On PR: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/
# On commit: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/

specfile_path: rpm/gvisor-tap-vsock.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - make

jobs:
  - job: copr_build
    trigger: pull_request
    enable_net: true
    # keep in sync with https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next
    targets:
      - fedora-rawhide-aarch64
      - fedora-rawhide-x86_64
      - fedora-eln-aarch64
      - fedora-eln-x86_64
      - fedora-38-aarch64
      - fedora-38-x86_64
      - centos-stream+epel-next-8-x86_64
      - centos-stream+epel-next-8-aarch64
      - centos-stream+epel-next-9-x86_64
      - centos-stream+epel-next-9-aarch64
    additional_repos:
      - "copr://rhcontainerbot/podman-next"

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    enable_net: true
    branch: main
    owner: rhcontainerbot
    project: podman-next

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-rawhide
      - fedora-38

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-rawhide
      - fedora-38

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-38 # rawhide updates are created automatically
