###
### This example config implements the legacy behavior, same as
### you didn't provide any
###
log-level: info
stack:
    mtu: 1500
    subnet: 192.168.127.0/24
    gatewayIP: 192.168.127.1
    gatewayMacAddress: 5a:94:ef:e4:0c:dd
    dns:
        - name: containers.internal.
          records:
            - name: gateway
              ip: 192.168.127.1
            - name: host
              ip: 192.168.127.254
        - name: docker.internal.
          records:
            - name: gateway
              ip: 192.168.127.1
            - name: host
              ip: 192.168.127.254
    forwards:
        127.0.0.1:2222: 192.168.127.2:22
    nat:
        192.168.127.254: 127.0.0.1
    gatewayVirtualIPs:
        - 192.168.127.254
    dhcpStaticLeases:
        192.168.127.2: 5a:94:ef:e4:0c:ee
    vpnKitUUIDMacAddresses:
        c3d68012-0208-11ea-9fd7-f2189899ab08: 5a:94:ef:e4:0c:ee

###
### Using while testing
###
### go get -v .
### go test .
### go run . -config config.yaml
###
